name = "ovca"
type = "webpack"
workers_dev = true
webpack_config = "webpack.config.js"

[site]
bucket = "./public"
entry-point = "./"

[vars]
B=''
R=''
X=''
O=''
TOKEN="706378399:AAFMlm63OEqDOU6GvLI-m1msD8fUqJ4XMkA"