name = "gre4a"
type = "webpack"
workers_dev = true
webpack_config = "webpack.config.js"

[vars]
B=''
M=''
X=''
T=''
O=''
R=''
TOKEN="766829439:AAF9xNG7F5GKhV3KLPaTcB2-I5ys_mQ-IwY"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"