name = "vv0w"
type = "webpack"
workers_dev = true
webpack_config = "webpack.config.js"

[vars]
B=''
M=''
X=''
T=''
O=''
R=''
TOKEN="1900136029:AAEsue89E30KleF5OjpHWGIDDm_YcBei-9Q"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"